### ISSUE TITLE
different senses vs different subentries

### ISSUE THREAD

**Issue by IrenH** [clld/dictionaria#10]
turn subentries into new entries as is, but keep senses \sn within the same entries

**Comment by xrotwang** [comment]
There are entries which list different senses with different parts-of-speech. If these are still to be treated as senses of the same word, we could

- either aggregate all parts-of-speech values for the single senses as part-of-speech of the word
- or store part-of-speech together with the counterpart object, i.e. the relation object between word and meaning - but we only have these relation objects in case of a counterpart for a comparison meaning.

**Comment by IrenH** [comment]
okay, these cases should be disallowed by us in the submission guidelines, the rule ought to be that different senses can only exist for the same POS, but different POS constitute a new entry, thank you for pointing this out

**Comment by xrotwang** [comment]
So this should be fixed in the submitted dictionaries and not by the code importing the dictionaries into the journal, right?

**Comment by IrenH** [comment]
yes, indeed! i will make a note of it in the submission guidelines, meanwhile different senses belonging to the same POS should be accumulated somehow, without destroying relations to examples of different senses, how may this be done?

**Comment by xrotwang** [comment]
Couldn't this be a relation between words? Homonymy?

**Comment by IrenH** [comment]
yes indeed

**Comment by xrotwang** [comment]
Ok. So we keep on splitting, but add relations to make it possible to re-assemble an entry with multiple senses. In that case, we could also allow different part-of-speech tags for different \sn blocks, because we could only add homonymy relations if the part-of-speech is the same.

**Comment by IrenH** [comment]
it may be difficult sometime to then distinguish between true homonyms and just different senses, I think Martin is working on this too right now, he will send a suggestion soon, for now this may be a good solution though..
how do you currently deal with \de's or \ge's which have semicolons in them? e.g. \ge wind ; storm are these split?

**Comment by xrotwang** [comment]
nope. No processing of \ge or \de so far. I think this kind of thing should not be allowed, because it introduces all sorts of edge cases, e.g. `\ge wind; storm` and `\de wind; strong wind; hurrivane` in the same entry. Which `\de` part to relate to which `\ge`?

**Comment by IrenH** [comment]
well, Toolbox allows this, and I know people do make use of it as an alternative to different senses... we might have to deal with it in one way or another... \ge is always more broad in meaning than \de or indeed different senses, I think people may have entries with just one \ge wind but either different \de's wind \de storm, or \de wind, storm
I think at leas commas in \de's should not make for a splitting and they need to be disallowed in \ge

**Comment by xrotwang** [comment]
So the separator in Toolbox is always `;` - or is this configurable?

**Comment by IrenH** [comment]
it usually is a a semicolon with a blank space before and after it
