### ISSUE TITLE
dictionaria-cldf module

### ISSUE THREAD

**Issue by xrotwang** [clld/dictionaria#15]
We should specify a cldf module or component as source format for dictionaria submissions. Metadata, lemmas, examples and sources can readily be mapped to the files defined for the [core cldf](https://github.com/glottobank/cldf#core-format-specification) dataset package. We will have to figure out, whether we want normalize meaning descriptions, which would result in another file.

**Comment by IrenH** [comment]
what do you mean by "normalizing meaning descriptions"?

**Comment by xrotwang** [comment]
normalization here means that there would be a list of unique meaning descriptions which is referenced from lemmas; thus avoiding duplication of meaning descriptions.

**Comment by IrenH** [comment]
but here will be not too many cases like this, will there? especially if meaning descriptions can be sets such as 'red / pink'

**Comment by xrotwang** [comment]
yes. unless we want to normalize even more, i.e. split into two descriptions "red" and "pink" and have a file listing the many-to-many relations between lemma and meaning.

**Comment by IrenH** [comment]
I think this is something we should discuss

**Comment by xrotwang** [comment]
see https://github.com/glottobank/cldf/tree/master/modules/dictionary
