### ISSUE TITLE
create sytax for md.json 

### ISSUE THREAD

**Issue by IrenH** [clld/dictionaria#26]
it would be good if we could specify the order of dictionary fields (in which they will be displayed in the web app) directly in the md.json file

**Comment by xrotwang** [comment]
The simplest syntax to specify an ordering among the fields of an entry would be to turn what is now a dictionary (aka associative array) into a list of pairs: https://github.com/clld/dictionaria-intern/commit/f565ee4db30268252540486d2de474b3388a3faf

**Comment by IrenH** [comment]
It looks the same, do I have to do anything different? Thanx!

**Comment by xrotwang** [comment]
This file isn't read from the web application on the fly. So to make changes take effect, I have to recreate the database.
