### ISSUE TITLE
make FTS also available for examples

### ISSUE THREAD

**Issue by IrenH** [clld/dictionaria#34]
Would it be possible to also make the FTS available throughout the examples? Ideal would be that FTS searches across both files at the same time for hits (examples.sfm and db.sfm),

**Comment by xrotwang** [comment]
I'm not sure I understand fully. Should the example text be indexed together with (each) entry it is referenced from - i.e. do we want to be able to find entries by example content? Or is this about FTS functionality to find examples?

**Comment by IrenH** [comment]
Yes,, I think it would be good if we were able to also find entries by example contents. 

How do you mean "find examples"? Find out whether entries have examples?

**Comment by xrotwang** [comment]
No, find particular examples - i.e. a FTS column on the table of examples.

**Comment by IrenH** [comment]
an FTS columm on the examples tab would also be great, then this one would only search within examples.sfm, but FTS on the main tab should ideally search through both, would this be doable?

**Comment by xrotwang** [comment]
FTS column on examples would not do much, I guess, because basically all fields of an example are available for search anyway. Search example content as well for the FTS column on entries otoh may increase the potential of confusion, because - e.g. for teopfish - the amount of example content may result in some entries being found for all sorts of searches, without an immediate control for the user why that is.

**Comment by IrenH** [comment]
true, and true...  then we will somehow have to document this somehow, and explain why the FTS works the way it does... Kilu wanted the FTS with examples included.

**Comment by xrotwang** [comment]
ok, example content is now indexed, too, see http://dictionaria.clld.org/contributions/daakaka#twords
I'd like to switch to a toolbox-independent format to display the full entry, though. While file:///tmp/mozilla_shh%5Cforkel0/daakaka-10-1.snippet.html may look familiar to toolbox users, we wouldn't want to format excel-based dictionaries in the same way.

**Comment by IrenH** [comment]
that is true, do you have a good suggestion as to how we can display the raw data?
