### ISSUE TITLE
add " Search help" to main menu

### ISSUE THREAD

**Issue by IrenH** [clld/dictionaria#43]
in order to make dictionaria more user friendly, we intend to create some simple Search and Browse help hints. we will need an extra page for this which can be accessed from anywhere in dictionaria therefore it would make sense to add this to the main menu bar

**Comment by xrotwang** [comment]
Help content can be added here: https://github.com/clld/dictionaria/blob/master/dictionaria/templates/help.mako

**Comment by IrenH** [comment]
Great!! Thank you!
