### ISSUE TITLE
Allow specification of dropdown-search for custom columns in tables

### ISSUE THREAD

**Issue by xrotwang** [clld/dictionaria#44]
Often custom attributes of entries have categorical values and it would be more usable if they could be searched and filtered using a dropdown-list of available values.

**Comment by stevepepper** [comment]
Note that the subset of values displayed might be dependent on the value selected in another dropdown-list. Specifically (for example):

IF "Part of speech" = "Noun" THEN display "Masc", "Fem" and "Proper"
IF "Part of speech" = "Verb" THEN display "Trans", "Intrans", "Caus1" and "Caus2"

**Comment by xrotwang** [comment]
I see that this would be desirable, but I don't think I'll implement it. It basically means you'd have to run the query before you can populate the user interface. This would destroy the whole point of using asynchronous requests to retrieve the data. It also wouldn't work with paging; i.e. you'd have to retrieve **all** results matching a set of filters, because you wouldn't want to only limit the choices in the dropdown lists to values on a particular page of results.
