### ISSUE TITLE
change default sorting of table

### ISSUE THREAD

**Issue by IrenH** [clld/dictionaria#49]
please change the default sorting in Words and Words Extra from primary key to headword

**Comment by IrenH** [comment]
somehow this still doesn't seem to work :/ at least not in the internal version

**Comment by xrotwang** [comment]
Which table? And what's the expected behaviour?

IrenH <notifications@github.com> schrieb am Do., 29. März 2018, 08:58:

**Comment by IrenH** [comment]
sidaama lex words, is not sorted by headword

**Comment by IrenH** [comment]
default sorting should be alphabetically by headword
