### ISSUE TITLE
TSE sources

### ISSUE THREAD

**Issue by IrenH** [clld/dictionaria#51]
e.g. http://matthew.clld.org/dictionaria/units/tseltal-TSE01352

in the sources box please display full label of field instead of TB field name, e.g. (meaning description instead of de)

**Comment by xrotwang** [comment]
Is this still a problem? I cannot locate a "sources box" on the linked page - maybe the example is outdated.

**Comment by IrenH** [comment]
interestingly enough, the sources seem to have disappeared.... :o how did that happen??

**Comment by xrotwang** [comment]
They are still there, e.g. http://matthew.clld.org/dictionaria/units/tseltal-TSE01161
and the issue seems to be resolved, i.t. the full label is displayed.

**Comment by IrenH** [comment]
hmm.. this examples showcases a different problem though... how do we kmnow which scientific name the source refers to? there are 2 fields of the kind in this entry

**Comment by xrotwang** [comment]
in the toolbox file:
```
(dictionaria)dlt5502178l:~/venvs/dictionaria/dictionaria-intern$ grep bibref submissions-internal/tseltal/db.sfm | wc -l
309
```
and in the database:
```
dictionaria_internal=# select count(*) from wordreference;
 count 
-------
   305
(1 row)
```

**Comment by IrenH** [comment]
I guess the previous example was wrong, sorry

**Comment by xrotwang** [comment]
yes, `\bibref` in this case would possibly be sense-specific ... And down the rabbit hole we go. But again, I think this should be solved by putting all of this half-normalized context into one separate comment field.

**Comment by IrenH** [comment]
yes, for the references this should work, but I am still nor sure how to solve the problematic "\de when TSE... is part of the text" sort of cases.. :(

**Comment by xrotwang** [comment]
Well, I would look at it from a database perspective: I would expect the content of the same column in a table to be of the same data type across dictionaries. For `\de` this data type is "text", I assume, not "html". Thus, links cannot be stored in this column.

**Comment by IrenH** [comment]
sure, that is why we will put them into new fields /columns, however, it will make the text very hard to read and i have not found a satisfying solution to that... it will break up the text...

**Comment by xrotwang** [comment]
Yes, but if it turns out that a dictionary is better read/understood as a sequence of short articles which explain the words, then the basic assumption of dictionaria was wrong. Since I still think machine readability has been underestimated so far, I'd happily sacrifice some human readability to explore the dictionaria idea a bit further.

**Comment by IrenH** [comment]
we'll have to find a way to accomodate the tseltal dictionary... maybe we can try modifying three entries inthe way you suggested and then ssend the resulg (as it looks on the web) to the author for approval?

**Comment by xrotwang** [comment]
Yes, maybe. Having the feedback loop go through the web view always is somewhat tedious, though.

**Comment by IrenH** [comment]
It seems to me that there will be no other solution forthcoming  to the links problem so a preview will be the only way to help the author understand what this will mean... unless there is still another way of dealign with this?
