### ISSUE TITLE
bring Tseltal online in official dictionaria

### ISSUE THREAD

**Issue by IrenH** [clld/dictionaria#71]
this is important, now that Tseltal has been converted to CLDF can it please go online with all the functionality it deserves? :) thanks!!!

**Comment by xrotwang** [comment]
So, are the media files incorporated in the CLDF now?

**Comment by IrenH** [comment]
yes :)

**Comment by IrenH** [comment]
OMG, please, please take it back!!! I didn't knwo this issue was still there!
GP has a crowd funding thing going and we cannot publish Tseltal until it is finished in a couple of weeks, lest it will harm him

**Comment by xrotwang** [comment]
I closed the issue, because obviously there's still issues to work on for this dict - not because I published it.
