### ISSUE TITLE
differentiate \de and \ge contents

### ISSUE THREAD

**Issue by IrenH** [clld/dictionaria#9]
in the "meaning description" column list all contents form \de as is  but all contents from \ge in small caps

**Comment by xrotwang** [comment]
Will we have the equivalents of \de and \ge for all dictionaries? If so, what are they called?
If not, this would already be a dictionary-specific handling, of which we want to have as few as possible.

**Comment by IrenH** [comment]
I guess we can expect \de and \ge in most dictionaries \de = definition English, \ge = gloss English, glosses are mostly one word items or abbrieviations that are used in the interlinearization of texts, \de is often more descriptive and offes more information, if a lexicon has both \de is the preferred field to be displayed, \ge will then mostly just contain grammatical glosses for those entries that do not have \de and can be ignored in the rest
